### ISSUE TITLE
[Bug]: The test case "test_snapshot_and_restore" sometimes fails.

### ISSUE THREAD

**Issue by Phoenix500526** [datenlord/Xline#240]
### Description about the bug

As the issue title, the test case "test_snapshot_and_restore" sometimes fails for unknown reasons in our CI workflow. I'm trying to reproduce this problem.

### Version

0.1.0 (Default)

### Relevant log output

```shell
---- test_snapshot_and_restore stdout ----
thread 'test_snapshot_and_restore' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', xline/tests/maintenance.rs:39:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by themanforfree** [comment]
The reason for this bug is that we take the snapshot too early,`maintenance_client` will send `SnapshotRequest` to a random server, other servers will call `after_sync` later than leader, after receiving the `SnapshotRequest`, the server may not have synchronized the previous command.
I solved this bug by making the `SnapshotRequest` only send to the leader, and after we finished our own client, we can use `propose_index` instead of `sleep` 100ms
