### ISSUE TITLE
Refactor: refactor the watch server implementation

### ISSUE THREAD

**Issue by Phoenix500526** [datenlord/Xline#253]
Currently, there are some problems with our watch server implementation.

## Spawning a task for every watch rpc call is not an efficient practice. 
Every watch rpc call will spawn a task. This is not an efficient practice. 
```Rust
impl<S> WatchServer<S>
where
    S: StorageApi,
{
    /// bg task for handle watch connection
    #[allow(clippy::integer_arithmetic)] // Introduced by tokio::select!
    async fn task<ST, W>(
        kv_watcher: Arc<W>,
        res_tx: mpsc::Sender<Result<WatchResponse, tonic::Status>>,
        mut req_rx: ST,
    ) where
        ST: Stream<Item = Result<WatchRequest, tonic::Status>> + Unpin,
        W: KvWatcherOps,
    {
        let (event_tx, event_rx) = mpsc::channel(CHANNEL_SIZE);
        let (stop_tx, stop_rx) = flume::bounded(0);
        let mut watch_handle = WatchHandle::new(kv_watcher, res_tx, event_rx, event_tx, stop_tx);
        loop {
            tokio::select! {
                req = req_rx.next() => {
                    if let Some(req) = req {
                        match req {
                            Ok(req) => {
                                watch_handle.handle_watch_request(req).await;
                            }
                            Err(e) => {
                                warn!("Receive WatchRequest error {:?}", e);
                                break;
                            }
                        }
                    } else {
                        warn!("Watch client closes connection");
                        break;
                    }
                }
                event = watch_handle.event_rx.recv() => {
                    if let Some(event) = event {
                        watch_handle.handle_watch_event(event).await;
                    } else {
                        panic!("Watch event sender is closed");
                    }
                }
                _ = stop_rx.recv_async() => {
                    break;
                }
            }
        }
    }
}

#[tonic::async_trait]
impl<S> Watch for WatchServer<S>
where
    S: StorageApi,
{
    ///Server streaming response type for the Watch method.
    type WatchStream = ReceiverStream<Result<WatchResponse, tonic::Status>>;

    /// Watch watches for events happening or that have happened. Both input and output
    /// are streams; the input stream is for creating and canceling watchers and the output
    /// stream sends events. One watch RPC can watch on multiple key ranges, streaming events
    /// for several watches at once. The entire event history can be watched starting from the
    /// last compaction revision.
    async fn watch(
        &self,
        request: tonic::Request<tonic::Streaming<WatchRequest>>,
    ) -> Result<tonic::Response<Self::WatchStream>, tonic::Status> {
        debug!("Receive Watch Connection {:?}", request);
        let req_stream = request.into_inner();
        let (tx, rx) = mpsc::channel(CHANNEL_SIZE);
        let _hd = tokio::spawn(Self::task(Arc::clone(&self.watcher), tx, req_stream));
        Ok(tonic::Response::new(ReceiverStream::new(rx)))
    }
}
```

## What would happen if a bounded channel block? Will it lose some watch events or block the watch server?

Our watch server uses a bounded channel to communicate whose default size is 128. This size may be too small.  What would happen when the channel is full? Will it cause the watch task block or some watch events to lose? I recommend adding a timeout mechanism for this issue, and when the send method is blocked, we will put this message into a data structure, like `victims` in etcd. And there is a victim_sync background task that will Periodically scan the victims and retry to send it.

## It may cause our watch feature to function abnormally.

Reading #252 for more details. This issue may be related to the current watch server implementation.

**Comment by themanforfree** [comment]
> Spawning a task for every watch rpc call is not an efficient practice.

I think this is necessary.  

If we didn't spawn a task for every watch rpc call, the request streams generated by multiple clients need to be merged into one place for processing, in order to distinguish the requests generated by different clients, we need a data structure to save the request stream and its corresponding client information, and we need a lock to protect it, which not only makes the performance worse but also makes the request processing process more complicated. In fact, our current method is similar to etcd, Etcd will also spawn goroutines for each watch rpc call, etcd uses two goroutines to separately process the request stream and response stream of a watch RPC call. We just combine these two operations into one task.  

But I think there is a point that can be optimized.  this our current watch logic:
![image](https://user-images.githubusercontent.com/56149350/236501333-ec135b70-cb74-4429-9a9a-80194e6c1de0.png)
The request part cannot be separated from the task, but the response can. On the watcher, we can directly bind the corresponding response stream of the watcher. We can directly return from the watcher to the client without going through the task. after this change, it looks like this:
![image](https://user-images.githubusercontent.com/56149350/236502274-f3c520e3-c3e9-4fc7-adbf-62a9872b678d.png)

**Comment by themanforfree** [comment]
> What would happen if a bounded channel block? Will it lose some watch events or block the watch server?

It will block all new events

To fix this, we can add `victims` and background task, Try to restore the blocking Watcher asynchronous in the background.

![image](https://github.com/datenlord/Xline/assets/56149350/bbfc0fbe-e073-420d-a18b-3ca6d46f65df)

The background task will try to send pending events in the `victims`, if send successful, it will try to fetch and send any new events generated during the watcher's recovery period. If any step of the sending precess fails, the watcher will be insert into the `victims` again, and wait for the next attempt.
